# Generated by Django 6.0 on 2025-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active (Currently Borrowed)'), ('RETURNED', 'Returned (Waiting for Owner Check)'), ('CLOSED', 'Closed (Completed)'), ('CANCELED', 'Canceled')], default='REQUESTED', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
