# Generated by Django 6.0 on 2025-12-19 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
        ('reviews', '0001_initial'),
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.review'),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='tools.tool'),
        ),
        migrations.AddConstraint(
            model_name='borrowrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REJECTED', 'CLOSED', 'CANCELED']), _negated=True), fields=('tool', 'borrower', 'status'), name='unique_active_request'),
        ),
    ]
