# Generated by Django 6.0 on 2025-12-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_type', models.CharField(choices=[('TOOL', 'Review of Tool'), ('BORROWER', 'Review of Borrower (by Owner)'), ('OWNER', 'Review of Owner (by Borrower)')], max_length=50)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='borrowing.borrowrequest')),
            ],
        ),
    ]
