# Generated by Django 6.0 on 2025-12-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='district',
            field=models.CharField(choices=[('Kollam', 'Kollam'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Wayanad', 'Wayanad'), ('Kasargod', 'Kasargod'), ('Pathanamthitta', 'Pathanamthitta')], default='Unknown', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='phone',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
